name: Deploy Branch Preview
on:
  push:
    branches-ignore:
      - main
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy branch to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # wherever your index.html lives
          destination_dir: ${{ github.ref_name }}
          keep_files: true
